apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid-testing
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: us-east1-docker.pkg.dev/covid-testing-bot/covid-repo/covid-testing:v6
            imagePullPolicy: IfNotPresent
            name: covid-testing
          restartPolicy: OnFailure
